[theme]
base="light"
primaryColor="#121212"
secondaryBackgroundColor="#ecf5fa"


[deprecation]
showPyplotGlobalUse = false


[server]
# Max size, in megabytes, of messages that can be sent via the WebSocket
# connection.
# Default: 200
maxMessageSize = 800
